# Generated by Django 2.2 on 2022-05-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='book_category', to='book.Category', verbose_name='Category'),
        ),
    ]
