# Generated by Django 2.2 on 2022-05-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20220512_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='upload_date',
            field=models.DateField(blank=True, null=True, verbose_name='Upload Date'),
        ),
    ]
